#%RAML 1.0 DataType
description: Account object data type

properties:
  id: string
  name: string
  number: string
  bill_street: string
  bill_city: string
  bill_state: string
  bill_zip: string
  phone: string

example:
  {
    "id": "0013i000004lRTXAA2",
    "name": "Xenon",
    "number": "A1234",
    "bill_street": "3292 Redbull st",
    "bill_city": "SFO",
    "bill_state": "CA",
    "bill_zip": "94116",
    "phone": "(415)930-3933"
  }