#%RAML 1.0 NamedExample

Accounts:
  [{
      "id": "0013i000004lRTXAA2",
      "name": "Xenon",
      "number": "A1234",
      "bill_street": "3292 Redbull st",
      "bill_city": "SFO",
      "bill_state": "CA",
      "bill_zip": "94116",
      "phone": "(415)930-3933"
    },

    {
        "id": "0013i000004lRTXAA4",
        "name": "Neon",
        "number": "A1233",
        "bill_street": "3292 Yellowbull st",
        "bill_city": "SFO",
        "bill_state": "CA",
        "bill_zip": "94113",
        "phone": "(415)930-0033"
    }
  ]